influx:
  host: "https://us-east-1-1.aws.cloud2.influxdata.com/api/v2/write"
  #"https://us-east-1-1.aws.cloud2.influxdata.com/api/v2/write?org=iot&bucket=iot&precision=s"
  token: "Token b1B2mmbWp9wnaLJsFOiXna_IeS8PdanJq1MClHZoTOSWmzg8SyiZSkq6Rwx4tCNPcLezg74OJd8BXajwWnfiqQ=="
  org: iot
  bucket: iot

sensors:
  ATC_334433:
    bucket: sofiarr
    tags: "room=hol"
    type: mitemp
