esphome:
  name: boikovec
  on_boot:
    priority: 600
    then:
      - esp32_ble_tracker.stop_scan
      - delay: 7s
      - esp32_ble_tracker.start_scan

esp32:
  board: esp32dev
  framework:
    type: arduino
    #version: 2.0.4


# Enable logging
logger:
  level: DEBUG

ota:
  password: !secret ota.password 

wifi:
  networks:
    - ssid: !secret wifi_ssid_boi
      password: !secret wifi_password_boi
    - ssid: !secret wifi_ssid_sof
      password: !secret wifi_password_sof

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Boikovec Fallback Hotspot"
    password: "HePlVGRcVEZG"

#captive_portal:
http_request:
  useragent: esphome/device
  timeout: 10s

esp32_ble_tracker:
 scan_parameters:
   interval: 300ms # try with 300ms if you don't have LAN module
   window: 300ms # try with 300ms if you don't have LAN module
   duration: 300s
   active: false
   continuous: true
 on_scan_end:
    - then:
      - esp32_ble_tracker.start_scan
 
xiaomi_ble:

interval:
  - interval: 1min
    then:
      - http_request.post:
          url: !secret bridge_url
          headers:
            Authorization: !secret influx_token
            target_url   : !secret target_url
            Content-Type : "application/text"
          body: !lambda |-
            std::string res;
            char buf[200];
            for (auto *obj : App.get_sensors()) {
              ESP_LOGD("main", "sensor id=%s, name=%s, state %f", obj->get_object_id().c_str(), obj->get_name().c_str(), obj->get_state());
              if (std::isnan(obj->get_state())) continue;
              sprintf(buf, "%s%f\n", obj->get_name().c_str(), obj->get_state());
              res += buf;
              ESP_LOGD("main", buf);
              obj->state = std::numeric_limits<double>::quiet_NaN();
            }
            return res.c_str();    

sensor:
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:2C:4B:CE"
    temperature:
      name: "boikovec,room=hol,type=mi,id=2C4BCE temp="
      filters:
        throttle_average: 60s
    humidity:
      name: "boikovec,room=hol,type=mi,id=2C4BCE humidity="
      filters:
        throttle_average: 1800s
    battery_voltage:
      name: "boikovec,room=hol,type=mi,id=2C4BCE voltage="
      filters:
        throttle_average: 3600s
  - platform: pvvx_mithermometer 
    mac_address: "A4:C1:38:DE:47:C1"
    temperature:
      name: "boikovec,room=hol,type=mi,id=DE47C1 temp="
      filters:
        throttle_average: 60s
    humidity:
      name: "boikovec,room=hol,type=mi,id=DE47C1 humidity="
      filters:
        throttle_average: 1800s
    battery_voltage:
      name: "boikovec,room=hol,type=mi,id=DE47C1 voltage="
      filters:
        throttle_average: 3600s

mqtt:
  broker: test.mosquitto.org
  port: 1883
  #username: vlast3k
  #password: vlast155
  discovery: false
  topic_prefix: Boikovec_ignore

